config/routes.rb
Movietime::Application.routes.draw do
  resources :directory_name_cleanup_patterns


  resources :cast_members
  resources :directors
  resources :genres
  resources :sources
  resources :movies

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/models/source.rb
class Source < ActiveRecord::Base
  attr_accessible :description, :name, :path

  validates :name,
    :presence => true

  validates :path,
    :presence => true
end

app/controllers/sources_controller.rb
class SourcesController < ApplicationController
  # GET /sources
  # GET /sources.json
  def index
    @sources = Source.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sources }
    end
  end

  # GET /sources/1
  # GET /sources/1.json
  def show
    @source = Source.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @source }
    end
  end

  # GET /sources/new
  # GET /sources/new.json
  def new
    @source = Source.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @source }
    end
  end

  # GET /sources/1/edit
  def edit
    @source = Source.find(params[:id])
  end

  # POST /sources
  # POST /sources.json
  def create
    @source = Source.new(params[:source])

    respond_to do |format|
      if @source.save
        format.html { redirect_to @source, notice: 'Source was successfully created.' }
        format.json { render json: @source, status: :created, location: @source }
      else
        format.html { render action: "new" }
        format.json { render json: @source.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sources/1
  # PUT /sources/1.json
  def update
    @source = Source.find(params[:id])

    respond_to do |format|
      if @source.update_attributes(params[:source])
        format.html { redirect_to @source, notice: 'Source was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @source.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sources/1
  # DELETE /sources/1.json
  def destroy
    @source = Source.find(params[:id])
    @source.destroy

    respond_to do |format|
      format.html { redirect_to sources_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/sources_helper.rb
module SourcesHelper
end

app/views/sources/_form.html.erb
<%= simple_form_for(@source) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :path %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/sources/edit.html.erb
<h1>Editing source</h1>

<%= render 'form' %>

<%= link_to 'Show', @source %> |
<%= link_to 'Back', sources_path %>

app/views/sources/index.html.erb
<h1>Listing sources</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Path</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sources.each do |source| %>
  <tr>
    <td><%= source.name %></td>
    <td><%= source.description %></td>
    <td><%= source.path %></td>
    <td><%= link_to 'Show', source %></td>
    <td><%= link_to 'Edit', edit_source_path(source) %></td>
    <td><%= link_to 'Destroy', source, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Source', new_source_path %>

app/views/sources/new.html.erb
<h1>New source</h1>

<%= render 'form' %>

<%= link_to 'Back', sources_path %>

app/views/sources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @source.name %>
</p>

<p>
  <b>Description:</b>
  <%= @source.description %>
</p>

<p>
  <b>Path:</b>
  <%= @source.path %>
</p>


<%= link_to 'Edit', edit_source_path(@source) %> |
<%= link_to 'Back', sources_path %>