config/routes.rb
Movietime::Application.routes.draw do
  resources :directory_name_cleanup_patterns


  resources :cast_members
  resources :directors
  resources :genres
  resources :sources
  resources :movies

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  # GET /movies
  # GET /movies.json
  def index
    @end_time_hour = 21
    @end_time_minute = 30
    @check_end_time = false

    puts params

    # fixes for select2 ajax multiselect
    unless params[:q].nil?
      unless params[:q][:director_id_in].nil?
        params[:q][:director_id_in] = params[:q][:director_id_in][0].split(",")
        params[:q][:director_id_in].map!{|item| item.gsub(/\[/, '').gsub(/\]/, '')}
      end

      unless params[:q][:cast_members_id_in].nil?
        params[:q][:cast_members_id_in] = params[:q][:cast_members_id_in][0].split(",")
        params[:q][:cast_members_id_in].map!{|item| item.gsub(/\[/, '').gsub(/\]/, '')}
      end

      unless params[:q][:end_time_hour].nil?
        @end_time_hour = params[:q][:end_time_hour].to_i
      end

      unless params[:q][:end_time_minute].nil?
        @end_time_minute = params[:q][:end_time_minute].to_i
      end

      unless params[:q][:check_end_time].nil?
        @check_end_time = params[:q][:check_end_time].to_i == 1
      end
    else
      params[:q] = {"source_id_in" => [1], "s" => "created_at desc"}
    end
    
    max_length = @check_end_time ? (Date.today.to_time.to_i + @end_time_hour * 3600 + @end_time_minute * 60 - DateTime.now.to_i) / 60 : 1000000000

    @search = Movie.where("movies.length <= ?", max_length)
    @search = @search.search(params[:q])
    @movies_all = @search.result(:distinct => true)
    @movies = @movies_all.paginate(:page => params[:page], :per_page => 15)
    @search.build_condition if @search.conditions.empty?
    @search.build_sort if @search.sorts.empty?

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @movies_all }
    end
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @movie = Movie.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @movie }
    end
  end

  # GET /movies/new
  # GET /movies/new.json
  def new
    @movie = Movie.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @movie }
    end
  end

  # GET /movies/1/edit
  def edit
    @movie = Movie.find(params[:id])
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(params[:movie])

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render json: @movie, status: :created, location: @movie }
      else
        format.html { render action: "new" }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /movies/1
  # PUT /movies/1.json
  def update
    @movie = Movie.find(params[:id])

    respond_to do |format|
      if @movie.update_attributes(params[:movie])
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_filter.html.erb
<div id="movie-filter">
<%= search_form_for @search do |f| %>
  <div class="filter-block">
    <div class="ui-dropdown">
      <div class="dialog">
        <div class="pointer">
          <div class="arrow"></div>
          <div class="arrow_border"></div>
        </div>
        <div class="body">
          <div class="form">
            <div class="field-box">
              <%= f.hidden_field :director_id_in, class: 'select2 ajax', :multiple => true, :style => "width:100%", data: { placeholder: 'director', source: directors_path, multiple: true } %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="filter-block">
    <div class="ui-dropdown">
      <div class="dialog">
        <div class="pointer">
          <div class="arrow"></div>
          <div class="arrow_border"></div>
        </div>
        <div class="body">
          <div class="form">
            <div class="field-box">
              <%= f.hidden_field :cast_members_id_in, class: 'select2 ajax', :multiple => true, :style => "width:100%", data: { placeholder: 'cast members', source: cast_members_path, multiple: true } %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="filter-block">
    <div class="ui-dropdown">
      <div class="dialog">
        <div class="pointer">
          <div class="arrow"></div>
          <div class="arrow_border"></div>
        </div>
        <div class="body">
          <div class="form">
            <div class="field-box">
              <%= f.collection_select :source_id_in, Source.find(:all, :order => :name), :id, :name, {}, { :multiple => true, :style => "width:100%" } %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="filter-block">
    <div class="ui-dropdown">
      <div class="dialog">
        <div class="pointer">
          <div class="arrow"></div>
          <div class="arrow_border"></div>
        </div>
        <div class="body">
          <div class="form">
            <div class="field-box">
              <%= f.collection_select :genres_id_in, Genre.find(:all, :order => :name), :id, :name, {}, { :multiple => true, :style => "width:100%" } %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="filter-block">
    <%= f.text_field :name_or_plot_cont, :class => "span2 search", :placeholder => "search" %>
  </div>

  <div class="filter-block">
    <span>end time:</span>
    <%= check_box_tag "q[check_end_time]", "1", @check_end_time, {:title => "check the end time"} %>
    <%= select_tag "q[end_time_hour]", options_for_select((0..23).collect{ |i| ["%02d" % i, i] }, @end_time_hour), :class => "time-select" %>:
    <%= select_tag "q[end_time_minute]", options_for_select([0, 15, 30, 45].collect{ |i| ["%02d" % i, i] }, @end_time_minute), :class => "time-select" %>
  </div>

  <div class="filter-block">
    <%= f.button '<i class="icon-filter"></i> Filter'.html_safe, :type => :submit, :class => 'btn primary' %>
      <span>or</span>
    <%= link_to t(:remove_filter), movies_path, :class => 'reset' %>
  </div>
<% end %>
</div>

app/views/movies/_form.html.erb
<%= simple_form_for(@movie) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :rating %>
    <%= f.input :votes %>
    <%= f.input :length %>
    <%= f.input :trailer_url %>
    <%= f.input :plot %>
    <%= f.input :plot_synopsis %>
    <%= f.input :plot_summary %>
    <%= f.input :poster_url %>
    <%= f.input :tagline %>
    <%= f.input :year %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<h1>Listing movies (<%= @movies_all.count %>)</h1>

<div class="row">
  <div class="pull-right">
    <%= render 'filter', :resource => @search %>
  </div>
</div>

<table id="movie_list">
  <colgroup>
    <col />
    <col width="*" />
    <col />
    <col />
    <col />
    <col />
    <col width="400" />
  </colgroup>
  <tr>
    <th></th>
    <th><%= sort_link @search, :name, "Name", {:page => params[:page]} %></th>
    <th><%= sort_link @search, :rating, "Rating", {:page => params[:page]} %></th>
    <th><%= sort_link @search, :length, "Length", {:page => params[:page]} %></th>
    <th><%= sort_link @search, :year, "Year", {:page => params[:page]} %></th>
    <th><%= sort_link @search, :created_at, "Created", {:page => params[:page]} %></th>
    <th></th>
  </tr>

<% @movies.each do |movie| %>
  <tr valign="top">
    <td>
      <% if movie.poster_image.exists? %>
        <a title="<%= movie.name %> (<%= movie.year %>) - <%= Time.at(movie.length * 60).utc.strftime("%kh %Mmin") %> - imdb <%= movie.rating %>" class="poster_lightbox" href="<%= movie.poster_image.url(:fullscreen) %>" data-lightbox="movies"><%= image_tag movie.poster_image.url(:small) %></a>
      <% elsif movie.poster_url %>
        <a title="<%= movie.name %> (<%= movie.year %>) - <%= Time.at(movie.length * 60).utc.strftime("%kh %Mmin") %> - imdb <%= movie.rating %>" class="poster_lightbox" href="<%= movie.poster_url %>" data-lightbox="movies"><img src="<%= movie.poster_url %>" alt="<%= movie.name %>" /></a>
      <% end %>
    </td>
    <td colspan="5">
      <div class="title">
        <span class="name"><%= movie.name %></span>
        (<%= movie.year %>)
        <a data-toggle="tooltip" title="YouTube trailers" target="_blank" href="<%= movie.youtube_trailer_url %>"><i class="icon icon-film"></i></a>
        <a data-toggle="tooltip" title="IMDB page" target="_blank" href="<%= movie.imdb_url %>"><i class="icon icon-info-sign"></i></a>
      </div>
      <div class="tagline">
        <small><%= movie.tagline.html_safe unless movie.tagline.nil? %></small>
      </div>
      <div class="lenght">
        <%= Time.at(movie.length * 60).utc.strftime("%kh %Mmin") %> - <i class="icon icon-star-empty"></i> <span data-toggle="tooltip" title="<%= movie.votes %> votes"><%= movie.rating %></span> - <span data-toggle="tooltip" title="director"><%= movie.director.name %></span>
      </div>
      <div class="genres">
        <% movie.genres.each do |genre| %>
          <span class="label label-info"><%= genre.name %></span>
        <% end %>
      </div>
      <div class="operators">
        <a target="_blank" href="file://<%= movie.full_path %>"><i class="icon icon-folder-open"></i></a>
        <%= link_to '<i class="icon icon-eye-open"></i>'.html_safe, movie %>
        <%= link_to '<i class="icon icon-edit"></i>'.html_safe, edit_movie_path(movie) %>
        <%= link_to '<i class="icon icon-remove"></i>'.html_safe, movie, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    </td>
    <td>
      <ul class="movie_tabs nav nav-tabs">
        <li class="active"><a href="#movie<%= movie.id %>-plot">Plot</a></li>
        <li><a href="#movie<%= movie.id %>-plot-summary">Plot Summary</a></li>
        <li><a href="#movie<%= movie.id %>-plot-synopsis">Plot Synopsis</a></li>
        <li><a href="#movie<%= movie.id %>-cast">Cast</a></li>
      </ul>
      <div class="tab-content">
        <div class="tab-pane plot active" id="movie<%= movie.id %>-plot"><%= movie.plot unless movie.plot.nil? %></div>
        <div class="tab-pane plot" id="movie<%= movie.id %>-plot-summary"><%= movie.plot_summary unless movie.plot_summary.nil? %></div>
        <div class="tab-pane plot" id="movie<%= movie.id %>-plot-synopsis"><%= movie.plot_synopsis unless movie.plot_synopsis.nil? %></div>
        <div class="tab-pane cast-members" id="movie<%= movie.id %>-cast">
          <% movie.cast_members.each do |cast_member| %>
            <span class="label"><%= cast_member.name %></span>
          <% end %>
        </div>
      </div>
    </td>
  </tr>
<% end %>
</table>

<%= will_paginate @movies, :renderer => BootstrapPagination::Rails, :previous_label => "&#8249;", :next_label => "&#8250;" %>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @movie.name %>
</p>

<p>
  <b>Rating:</b>
  <%= @movie.rating %>
</p>

<p>
  <b>Votes:</b>
  <%= @movie.votes %>
</p>

<p>
  <b>Length:</b>
  <%= @movie.length %>
</p>

<p>
  <b>Trailer url:</b>
  <%= @movie.trailer_url %>
</p>

<p>
  <b>Plot:</b>
  <%= @movie.plot %>
</p>

<p>
  <b>Plot synopsis:</b>
  <%= @movie.plot_synopsis %>
</p>

<p>
  <b>Plot summary:</b>
  <%= @movie.plot_summary %>
</p>

<p>
  <b>Poster url:</b>
  <%= @movie.poster_url %>
</p>

<p>
  <b>Tagline:</b>
  <%= @movie.tagline %>
</p>

<p>
  <b>Year:</b>
  <%= @movie.year %>
</p>


<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>