config/routes.rb
Movietime::Application.routes.draw do
  resources :directory_name_cleanup_patterns


  resources :cast_members
  resources :directors
  resources :genres
  resources :sources
  resources :movies

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/models/directory_name_cleanup_pattern.rb
class DirectoryNameCleanupPattern < ActiveRecord::Base
  attr_accessible :pattern, :priority, :replace

  default_scope order('priority DESC')

  def search
    # eval: unsafe but ok here, because the app is self hosted
    self.pattern[0] == '/' ? Regexp.new(eval(self.pattern)) : self.pattern
  end

  def gsub!(str)
    str.gsub!(self.search, self.replace)
    return str
  end

  def self.cleanup(str)
  	result = str.clone
  	DirectoryNameCleanupPattern.all.each {|cleanup_pattern| result = cleanup_pattern.gsub!(result) unless result.nil?}
  	result.squeeze(' ').strip unless result.nil?
  end
end

app/controllers/directory_name_cleanup_patterns_controller.rb
class DirectoryNameCleanupPatternsController < ApplicationController
  # GET /directory_name_cleanup_patterns
  # GET /directory_name_cleanup_patterns.json
  def index
    @directory_name_cleanup_patterns = DirectoryNameCleanupPattern.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @directory_name_cleanup_patterns }
    end
  end

  # GET /directory_name_cleanup_patterns/1
  # GET /directory_name_cleanup_patterns/1.json
  def show
    @directory_name_cleanup_pattern = DirectoryNameCleanupPattern.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @directory_name_cleanup_pattern }
    end
  end

  # GET /directory_name_cleanup_patterns/new
  # GET /directory_name_cleanup_patterns/new.json
  def new
    @directory_name_cleanup_pattern = DirectoryNameCleanupPattern.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @directory_name_cleanup_pattern }
    end
  end

  # GET /directory_name_cleanup_patterns/1/edit
  def edit
    @directory_name_cleanup_pattern = DirectoryNameCleanupPattern.find(params[:id])
  end

  # POST /directory_name_cleanup_patterns
  # POST /directory_name_cleanup_patterns.json
  def create
    @directory_name_cleanup_pattern = DirectoryNameCleanupPattern.new(params[:directory_name_cleanup_pattern])

    respond_to do |format|
      if @directory_name_cleanup_pattern.save
        format.html { redirect_to @directory_name_cleanup_pattern, notice: 'Directory name cleanup pattern was successfully created.' }
        format.json { render json: @directory_name_cleanup_pattern, status: :created, location: @directory_name_cleanup_pattern }
      else
        format.html { render action: "new" }
        format.json { render json: @directory_name_cleanup_pattern.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /directory_name_cleanup_patterns/1
  # PUT /directory_name_cleanup_patterns/1.json
  def update
    @directory_name_cleanup_pattern = DirectoryNameCleanupPattern.find(params[:id])

    respond_to do |format|
      if @directory_name_cleanup_pattern.update_attributes(params[:directory_name_cleanup_pattern])
        format.html { redirect_to @directory_name_cleanup_pattern, notice: 'Directory name cleanup pattern was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @directory_name_cleanup_pattern.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /directory_name_cleanup_patterns/1
  # DELETE /directory_name_cleanup_patterns/1.json
  def destroy
    @directory_name_cleanup_pattern = DirectoryNameCleanupPattern.find(params[:id])
    @directory_name_cleanup_pattern.destroy

    respond_to do |format|
      format.html { redirect_to directory_name_cleanup_patterns_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/directory_name_cleanup_patterns_helper.rb
module DirectoryNameCleanupPatternsHelper
end

app/views/directory_name_cleanup_patterns/_form.html.erb
<%= simple_form_for(@directory_name_cleanup_pattern) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :pattern %>
    <%= f.input :replace %>
    <%= f.input :priority %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/directory_name_cleanup_patterns/edit.html.erb
<h1>Editing directory_name_cleanup_pattern</h1>

<%= render 'form' %>

<%= link_to 'Show', @directory_name_cleanup_pattern %> |
<%= link_to 'Back', directory_name_cleanup_patterns_path %>

app/views/directory_name_cleanup_patterns/index.html.erb
<h1>Listing directory_name_cleanup_patterns</h1>

<table>
  <tr>
    <th>Pattern</th>
    <th>Replace</th>
    <th>Priority</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @directory_name_cleanup_patterns.each do |directory_name_cleanup_pattern| %>
  <tr>
    <td><%= directory_name_cleanup_pattern.pattern %></td>
    <td><%= directory_name_cleanup_pattern.replace %></td>
    <td><%= directory_name_cleanup_pattern.priority %></td>
    <td><%= link_to 'Show', directory_name_cleanup_pattern %></td>
    <td><%= link_to 'Edit', edit_directory_name_cleanup_pattern_path(directory_name_cleanup_pattern) %></td>
    <td><%= link_to 'Destroy', directory_name_cleanup_pattern, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Directory name cleanup pattern', new_directory_name_cleanup_pattern_path %>

app/views/directory_name_cleanup_patterns/new.html.erb
<h1>New directory_name_cleanup_pattern</h1>

<%= render 'form' %>

<%= link_to 'Back', directory_name_cleanup_patterns_path %>

app/views/directory_name_cleanup_patterns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Pattern:</b>
  <%= @directory_name_cleanup_pattern.pattern %>
</p>

<p>
  <b>Replace:</b>
  <%= @directory_name_cleanup_pattern.replace %>
</p>

<p>
  <b>Priority:</b>
  <%= @directory_name_cleanup_pattern.priority %>
</p>


<%= link_to 'Edit', edit_directory_name_cleanup_pattern_path(@directory_name_cleanup_pattern) %> |
<%= link_to 'Back', directory_name_cleanup_patterns_path %>